BookApp/Controllers/BillingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookApp;
using BookApp.Models;

namespace BookApp.Controllers
{
    public class BillingsController : Controller
    {
        private readonly DatabaseContext _context;

        public BillingsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Billings
        public async Task<IActionResult> Index()
        {
              return _context.Billing != null ? 
                          View(await _context.Billing.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Billing'  is null.");
        }

        // GET: Billings/Details/5
   

        // GET: Billings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Billings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransactionId,Total_Payment,Payment_Type,Bank_Name,Branch,CreditCard_Number,CardExpiryDate,cvv")] Billing billing)
        {
           
            if (billing.Payment_Type == "COD")
            {
                billing.Branch = "null";
                billing.CreditCard_Number = "null";
                billing.cvv = "null";
                billing.CardExpiryDate = (DateTime.Today);
                billing.Bank_Name = "null";


            }
            var TransactionId = billing.TransactionId;
            billing.Total_Payment = Convert.ToInt32(HttpContext.Session.GetString("TotalAmt"));
            billing.User_Id = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            billing.DateTime = (DateTime.Today).ToShortDateString();
            billing.Book_Id = Convert.ToInt32(HttpContext.Session.GetString("Book_Id"));
            billing.Book_Name = HttpContext.Session.GetString("Book_Name").ToString();
                
            billing.Quantity = Convert.ToInt32(HttpContext.Session.GetString("Quantity"));
            HttpContext.Session.SetString("TransactionId", (TransactionId).ToString());
            Book book = _context.Book.FirstOrDefault(b => b.Book_Name == billing.Book_Name);
            book.Quantity = book.Quantity -billing.Quantity;
            _context.Add(billing);
                await _context.SaveChangesAsync();
                return View();
          
        }
        public async Task<IActionResult> Order()
        {
            

            var Items = await _context.Billing.FromSqlRaw("select *  from billing ").ToListAsync();
            return View(Items);
        }
        public async Task<IActionResult> CustomerOrders()
        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            var orItems = await _context.Billing.FromSqlRaw("select * from billing where  user_id = '" + id + "'  ").ToListAsync();
            return View(orItems);

        }
       
        // GET: Billings/Edit/5
       

        private bool BillingExists(int id)
        {
          return (_context.Billing?.Any(e => e.TransactionId == id)).GetValueOrDefault();
        }
    }
}

BookApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookApp;
using BookApp.Models;

namespace BookApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly DatabaseContext _context;

        public BooksController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
              return _context.Book != null ? 
                          View(await _context.Book.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Book'  is null.");
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, [Bind("Id,BookId,Book_Name,Author,Category,Description,Quantity,Price")] Book book)
        {
            if (file != null)
            {
                string filename = file.FileName;
              
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                book.ImageUrl = filename;
            }
            

            _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
       
        }
        public async Task<IActionResult> Catalogue(string search)
        {
            
            if (!String.IsNullOrEmpty(search))
            {
                var orItems = await _context.Book.FromSqlRaw("select *  from Book where  Category = '" + search + "'").ToListAsync();
                return View(orItems);
            }
    
            return View(await _context.Book.ToListAsync());
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, int id, [Bind("Id,BookId,Book_Name,Author,Category,Description,Quantity,Price,ImageUrl")] Book book)
        {
            if (file != null)
            {
                string filename = file.FileName;
              
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                book.ImageUrl = filename;
            }

            _context.Update(book);
                    await _context.SaveChangesAsync();
               
                return RedirectToAction(nameof(Index));
            
           
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Book == null)
            {
                return Problem("Entity set 'DatabaseContext.Book'  is null.");
            }
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookApp/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Json;
using Microsoft.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookApp;
using BookApp.Models;
using Newtonsoft.Json;

namespace BookApp.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly DatabaseContext _context;

        List<Transaction> list = new List<Transaction>();
     
        public CartItemsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            return _context.CartItems != null ? 
                          View(await _context.CartItems.FromSqlRaw("select *  from CartItems where  userid = '" + id + "'  ").ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.CartItems'  is null.");
        }




        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cartItems == null)
            {
                return NotFound();
            }

            return View(cartItems);
        }

        // GET: CartItems/Create
        public async Task<IActionResult> Create(int? id)
        {
            var book = await _context.Book.FindAsync(id);
            return View(book);
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int bookId, string bookName, string Author, string ImageUrl, int quantity,int price)
        {
            CartItems cart = new CartItems();
            cart.Book_Id = bookId;
            cart.Book_Name = bookName;
            cart.Author = Author;
            cart.ImageUrl = ImageUrl;
            cart.Quantity = quantity;
            cart.TotalAmt = quantity * price;
            cart.UserId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
     
            HttpContext.Session.SetString("Quantity", quantity.ToString());
            HttpContext.Session.SetString("Book_Id", (bookId).ToString());
            HttpContext.Session.SetString("Book_Name",bookName);
            HttpContext.Session.SetString("TotalAmt", (cart.TotalAmt).ToString());
            _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
   
        }
     
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems.FindAsync(id);
            if (cartItems == null)
            {
                return NotFound();
            }
            return View(cartItems);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Book_Id,Book_Name,Author,Quantity,TotalAmt,ImageUrl,UserId")] CartItems cartItems)
        {
            if (id != cartItems.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItems);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemsExists(cartItems.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cartItems);
        }

      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cartItems == null)
            {
                return NotFound();
            }

            return View(cartItems);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CartItems == null)
            {
                return Problem("Entity set 'DatabaseContext.CartItems'  is null.");
            }
            var cartItems = await _context.CartItems.FindAsync(id);
            if (cartItems != null)
            {
                _context.CartItems.Remove(cartItems);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemsExists(int id)
        {
          return (_context.CartItems?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor accessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                     @{
						try
						{

							if (accessor.HttpContext.Session.GetString("First_Name") != null)
							{
								string name = accessor.HttpContext.Session.GetString("First_Name");
								string? rollid = accessor.HttpContext.Session.GetString("Role");

								<ul class="navbar-nav flex-grow-1 justify-content-end ">

									@if (rollid != null)
									{
										if (rollid == "Admin")
										{
											 <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Create">Add Book</a>
                            </li>
                            <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Manage Books</a>
                            </li>
                            <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Billings" asp-action="Order">Order reports</a>
                            </li>
                            <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="Index">Customers List</a>
                            </li>
                            <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Billings" asp-action="Index">Bilings</a>
                            </li>
                            <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                            </li>
                           
										}
										else if (rollid == "User")
										{
											  <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Catalogue"> Catalogy</a>
                            </li>
                             <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CartItems" asp-action="Index">My Cart</a>
                            </li>
                            <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Billings" asp-action="CustomerOrders">My Orders</a>
                            </li>
                            
										}
									}
                                    <li class="nav-item btn btn-outline-primary" style="margin-left:1%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="ProfileView" >View profile</a>
                            </li>

									<li class="nav-item btn btn-primary text-white" style="margin-right:1%;">
										<a class="nav-link text-white" asp-area="" asp-controller="UserAccounts" asp-action="Index">Welcome, &nbsp; <span class="text-white">@name</span> </a>
									</li>
									<li class="nav-item btn btn-danger" style="margin-left:auto">
										<a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="Login">Logout</a>
									</li>
								</ul>


							}
						}
						catch { }
					}

				</div>
			</div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookApp/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"><ul>
                <li class="nav-item btn btn-outline-light text-white" style="margin-right:auto">
										<a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="Login" style="color:yellow" >Login</a>
									</li>    	</ul>
                </div>
			</div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
@*
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>