BookApp/Models/CartItems.cs
using System.ComponentModel.DataAnnotations;
namespace BookApp.Models
{
    public class CartItems
    {
        [Key]
        public int Id { get; set; }
        [Required]

        public int Book_Id { get; set; }
        [Required]
        public string Book_Name { get; set; }
        [Required]
        public string Author { get; set; }
 
        [Required]
        public int Quantity { get; set; }
        [Required]
        public int TotalAmt { get; set; }
        [Required]
        public string ImageUrl { get; set; }

        public int UserId { get; set; }

       
    }
}

BookApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookApp;
using BookApp.Models;

namespace BookApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly DatabaseContext _context;

        public BooksController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
              return _context.Book != null ? 
                          View(await _context.Book.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Book'  is null.");
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, [Bind("Id,BookId,Book_Name,Author,Category,Description,Quantity,Price")] Book book)
        {
            if (file != null)
            {
                string filename = file.FileName;
              
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                book.ImageUrl = filename;
            }
            

            _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
       
        }
        public async Task<IActionResult> Catalogue(string search)
        {
            
            if (!String.IsNullOrEmpty(search))
            {
                var orItems = await _context.Book.FromSqlRaw("select *  from Book where  Category = '" + search + "'").ToListAsync();
                return View(orItems);
            }
    
            return View(await _context.Book.ToListAsync());
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, int id, [Bind("Id,BookId,Book_Name,Author,Category,Description,Quantity,Price,ImageUrl")] Book book)
        {
            if (file != null)
            {
                string filename = file.FileName;
              
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                book.ImageUrl = filename;
            }

            _context.Update(book);
                    await _context.SaveChangesAsync();
               
                return RedirectToAction(nameof(Index));
            
           
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Book == null)
            {
                return Problem("Entity set 'DatabaseContext.Book'  is null.");
            }
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookApp/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Json;
using Microsoft.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookApp;
using BookApp.Models;
using Newtonsoft.Json;

namespace BookApp.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly DatabaseContext _context;

        List<Transaction> list = new List<Transaction>();
     
        public CartItemsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            return _context.CartItems != null ? 
                          View(await _context.CartItems.FromSqlRaw("select *  from CartItems where  userid = '" + id + "'  ").ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.CartItems'  is null.");
        }




        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cartItems == null)
            {
                return NotFound();
            }

            return View(cartItems);
        }

        // GET: CartItems/Create
        public async Task<IActionResult> Create(int? id)
        {
            var book = await _context.Book.FindAsync(id);
            return View(book);
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int bookId, string bookName, string Author, string ImageUrl, int quantity,int price)
        {
            CartItems cart = new CartItems();
            cart.Book_Id = bookId;
            cart.Book_Name = bookName;
            cart.Author = Author;
            cart.ImageUrl = ImageUrl;
            cart.Quantity = quantity;
            cart.TotalAmt = quantity * price;
            cart.UserId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
     
            HttpContext.Session.SetString("Quantity", quantity.ToString());
            HttpContext.Session.SetString("Book_Id", (bookId).ToString());
            HttpContext.Session.SetString("Book_Name",bookName);
            HttpContext.Session.SetString("TotalAmt", (cart.TotalAmt).ToString());
            _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
   
        }
     
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems.FindAsync(id);
            if (cartItems == null)
            {
                return NotFound();
            }
            return View(cartItems);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Book_Id,Book_Name,Author,Quantity,TotalAmt,ImageUrl,UserId")] CartItems cartItems)
        {
            if (id != cartItems.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItems);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemsExists(cartItems.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cartItems);
        }

      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CartItems == null)
            {
                return NotFound();
            }

            var cartItems = await _context.CartItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cartItems == null)
            {
                return NotFound();
            }

            return View(cartItems);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CartItems == null)
            {
                return Problem("Entity set 'DatabaseContext.CartItems'  is null.");
            }
            var cartItems = await _context.CartItems.FindAsync(id);
            if (cartItems != null)
            {
                _context.CartItems.Remove(cartItems);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemsExists(int id)
        {
          return (_context.CartItems?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookApp/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookApp;
using BookApp.Models;

namespace BookApp.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly DatabaseContext _context;

        public TransactionsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Transactions
        public async Task<IActionResult> Index()
        {
              return _context.Transaction != null ? 
              View(await _context.Transaction.ToListAsync()) :
              Problem("Entity set 'DatabaseContext.Transaction'  is null.");
        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Transaction == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transactions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Country,First_Name,Last_Name,Address,Apartment,city,state,Pin_Code,Phone_Number")] Transaction transaction)
        {

            transaction.User_Id= Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            _context.Add(transaction);
            await _context.SaveChangesAsync();
            return View();
          
        }

        // GET: Transactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Transaction == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Country,First_Name,Last_Name,Address,Apartment,city,state,Pin_Code,Phone_Number,User_Id")] Transaction transaction)
        {
            if (id != transaction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Transaction == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Transaction == null)
            {
                return Problem("Entity set 'DatabaseContext.Transaction'  is null.");
            }
            var transaction = await _context.Transaction.FindAsync(id);
            if (transaction != null)
            {
                _context.Transaction.Remove(transaction);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactionExists(int id)
        {
          return (_context.Transaction?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BookApp/Views/CartItems/Create.cshtml
@model BookApp.Models.Book

@{
    ViewData["Title"] = "Book Details";
}

<h1></h1>
<h4>Orders</h4>
<head>
<style>
  body{
        background-image:url('https://www.teahub.io/photos/full/190-1905135_background-images-of-books.png');
        background-repeat:no-repeat;
        background-attachment:fixed;
        background-size:cover;
   
    }
</style>
</head>
<hr />
 <dl class="row">
          
        <dt>
            Product Image
        </dt>
        <dd>
           <img src="~/images/@Model.ImageUrl" height="150" width="100" />
            <br />@Model.ImageUrl

        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book_Name)

        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
            </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
           <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
         <dt class = "col-sm-2">
           In Stock
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
            </dd>
      
    </dl>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="bookId" value=@Model.Id />
            <input type="hidden" name="bookName" asp-for="Book_Name"/>
             <input type="hidden" name="Author" asp-for="Author"/>
            <input type="hidden" name="ImageUrl" asp-for="ImageUrl" />
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" min="1" width="15%"/>
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <input type="hidden" name="price" asp-for="Price" />
           
            <div class="form-group">
                <input type="submit" value="Buy" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Books" asp-action="catalogue">Back to Catalogue</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookApp/Views/CartItems/Delete.cshtml
@model BookApp.Models.CartItems

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<head>
<style>
  body{
        background-image:url('https://www.teahub.io/photos/full/190-1905135_background-images-of-books.png');
        background-repeat:no-repeat;
        background-attachment:fixed;
        background-size:cover;
   
    }
</style>
</head>
<div>
    <h4>CartItems</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookApp/Views/CartItems/Details.cshtml
@model BookApp.Models.CartItems

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<head>
<style>
  body{
        background-image:url('https://www.teahub.io/photos/full/190-1905135_background-images-of-books.png');
        background-repeat:no-repeat;
        background-attachment:fixed;
        background-size:cover;
   
    }
</style>
</head>
<div>
    <h4>CartItems</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookApp/Views/CartItems/Edit.cshtml
@model BookApp.Models.CartItems

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CartItems</h4>
<hr />
<head>
<style>
  body{
        background-image:url('https://www.teahub.io/photos/full/190-1905135_background-images-of-books.png');
        background-repeat:no-repeat;
        background-attachment:fixed;
        background-size:cover;
   
    }
</style>
</head>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="Book_Name" class="control-label"></label>
                <input asp-for="Book_Name" class="form-control" readonly/>
                <span asp-validation-for="Book_Name" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" readonly/>
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
             
              <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmt" class="control-label"></label>
                <input asp-for="TotalAmt" class="form-control" readonly/>
                <span asp-validation-for="TotalAmt" class="text-danger"></span>
            </div>
            <img src="~/images/@Model.ImageUrl" height="150" />
         
            <input type="hidden" asp-for="ImageUrl" />

             <div class="form-group">
                <label class="control-label">Pic</label>
                <input type="file" class="form-control" name="file" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
     <a asp-controller="CartItems" asp-action="Index">Back to Cart</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookApp/Views/CartItems/Index.cshtml
@model IEnumerable<BookApp.Models.CartItems>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<head>

<style>
  body{
        background-image:url('https://www.teahub.io/photos/full/190-1905135_background-images-of-books.png');
        background-repeat:no-repeat;
        background-attachment:fixed;
        background-size:cover;
   
    }
</style>
</head>

<table class="table table-striped" border="1" width="100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Book_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Book_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Book_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmt)
            </td>
            <td>
               <img src="~/images/@item.ImageUrl" height="150" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>| 
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|
                <a asp-controller="Transactions" asp-action="create" asp-route-id="@item.Id" class="btn btn-outline-success" onclick="@item.Id=booked" >CheckOut</a>
            </td>
        </tr>
}
    </tbody>
</table>